//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VpnConnections.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VpnConnections.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon pnidui_3032 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3032", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3035 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3035", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3044 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3044", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3048 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3048", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3051 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3051", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3054 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3054", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3066 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3066", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3067 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3067", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3071 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3071", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3072 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3072", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3073 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3073", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3074 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3074", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3075 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3075", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3076 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3076", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3077 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3077", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3078 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3078", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3079 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3079", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3081 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3081", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3082 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3082", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3083 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3083", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3084 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3084", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3085 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3085", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3086 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3086", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3087 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3087", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3088 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3088", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3089 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3089", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3091 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3091", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3092 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3092", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3093 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3093", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3094 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3094", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3095 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3095", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_3096 {
            get {
                object obj = ResourceManager.GetObject("pnidui_3096", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_40405 {
            get {
                object obj = ResourceManager.GetObject("pnidui_40405", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_40406 {
            get {
                object obj = ResourceManager.GetObject("pnidui_40406", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pnidui_40407 {
            get {
                object obj = ResourceManager.GetObject("pnidui_40407", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
